/* 
tiene palabras y mensajes que se muestran en las diferentes pantallas de la aplicación. 
 De esta manera, si reemplazo el nombre de una accion (por ejemplo: la palabra “modificar” por “actualizar”), entonces no debería cambiar manualmente en cada lugar donde aparece dicha palabra,
 sino que solo cambiaría esa constante y automáticamente se cambiaría en todos los lugares donde se use la misma.

*/
export class Constantes {
    public _inicio = 'Inicio';
    public _acolitApp = 'AcolitApp';
    public _inicioSesion = 'Inicio de sesión';
    public _iniciarSesion = 'Iniciar sesión';
    public _registro = 'Registro';
    public _registrar = 'Registrar';
    public _datosPersonales = 'Datos personales';
    public _favor= 'Favor';
    public _favores= 'Favores';
    public _nuevoFavor= 'Nuevo Favor';
    public _solicitud= 'Solicitud';
    public _notificaciones= 'Notificaciones';
    public _favorRecibido= 'Favor recibido';
    public _personasDisponibles= 'Personas disponibles';
    public _pais= 'Pais';
    public _ciudad= 'Ciudad';
    public _ajustesNotificacion= 'Ajustes de notificación';
    public _ajustesFavores= 'Ajuste de Favores';
    public _ubicacionActual= 'Ubicación actual';
    public _ubicacionDetallada= 'Ubicación detallada';
    public _identificacion= 'Identificación';
    public _correoElectronico= 'Correo electrónico';
    public _usuario= 'Usuario';
    public _contrasenia= 'Contraseña';
    public _confirmarContrasenia= 'Confirmar contraseña';
    public _crearCuenta= 'Crear cuenta';
    public _cancela= 'Cancelar';
    public _nombresApellidos= 'Nombres y apellidos';
    public _nacionalidad= 'Nacionalidad';
    public _nivelEstudios= 'Nivel de estudios';
    public _profesion= 'Profesión';
    public _ocupacion= 'Ocupación';
    public _informacionAdicional= 'Información adicional';
    public _tipoVehiculo= 'Tipo de vehículo';
    public _licencia= 'Licencia';
    public _placaVehiculo= 'Placa del vehículo';
    public _otros= 'Otros';
    public _finalizar= 'finalizar';
    public _solicitados= 'solicitados';
    public _realizados= 'Realizados';
    public _favoresSolicitados= 'Favores solicitados';
    public _favoresRealizados= 'Favores realizados';
    public _cuenta= 'Cuenta';
    public _cerrarSesion= 'Cerrar sesión';
    public _titulo= 'Título';
    public _descripcion= 'Descripción';
    public _formaPago= 'Forma de pago';
    public _detalleObsequio= 'Detalle del obsequio';
    public _detalleFavor= 'Detalle del favor a intercambiar';
    public _valorMonetario= 'Valor monetario';
    public _valorPagar= 'Valor a pagar';
    public _calificacion= 'Calificación';
    public _obsequio= 'Obsequio';
    public _otroFavor= 'Otro favor';
    public _filtros= 'Filtros';
    public _filtro= 'Filtro';
    public _ubicacion= 'Ubicación';
    public _calificación= 'Calificación';
    public _realizar= 'Realizar';
    public _calificar= 'Calificar';
    public _descripcionObsequio= 'Descripcion del obsequio';
    public _aceptar= 'Aceptar';
    public _cancelar= 'Cancelar';
    public _puntuacion= 'Puntuación';
    public _informacionPersonal= 'Información personal';
    public _medioTransporte= 'Medio de transporte';
    public _valoresPredeterminados= 'Valores predeterminados';
    public _edad= 'Edad';
    public _desde= 'Desde';
    public _hasta= 'Hasta';
    public _seleccioneOcupacion= 'Seleccione la ocupación';
    public _seleccioneUbicacion= 'Seleccione la ubicación';
    public _licenciaConducir= 'Licencia de conducir';
    public _si= 'Si';
    public _no= 'No';
    public _tipoLicencia= 'Tipo de licencia';
    public _direccion= 'Dirección';
    public _telefono= 'Teléfono';
    public _callePrincipal= 'Calle principal';
    public _calleSecundaria= 'Calle secundaria';
    public _barrio= 'Barrio';
    public _numeroCasa= 'Número de casa';
    public _referencia= 'Referencia';
    public _expresionMail= '^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$';
    public _duracionToast= 2000;
    public _solicitar= 'Solicitar';
    public _todos= 'Todos';
    public _rechazar= 'Rechazar';
    public _cargandoDatos = 'Cargando datos...';
    public _guardandoDatos = 'Guardando datos...';
    public _fotoPerfil = 'Foto del Perfil'
    public _brindarAyuda= 'Brindar ayuda';
    public _ayudar= 'Ayudar';
    public _aceptarAyuda= 'Aceptar ayuda';
    public _rechazarAyuda= 'Rechazar ayuda';
    public _cancelarSolicitud= 'Cancelar solicitud';
    public _cancelarAyudar= 'Cancelar ayuda';
    public _guardar= 'Guardar';
    public _eliminando= 'Eliminando';
    public _cancelandoSolicitud= 'Cancelando solicitud';
    public _actualizandoDatos= 'Actualizando datos';


}